apiVersion: v1
kind: Service
metadata:
  name: proposal-service
spec:
  selector:
    app: proposal-service
  ports:
    - protocol: TCP
      port: 50052
      targetPort: 50052
  type: ClusterIP
