// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.1
// source: proto/proposal.proto

package proposal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateProposalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	FreelancerId  string                 `protobuf:"bytes,2,opt,name=freelancer_id,json=freelancerId,proto3" json:"freelancer_id,omitempty"`
	TemplateId    string                 `protobuf:"bytes,3,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"` // "draft" | "sent" | "accepted" | "rejected"
	Version       int32                  `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=deadline,proto3" json:"deadline,omitempty"`
	DeadlineStr   string                 `protobuf:"bytes,9,opt,name=deadline_str,json=deadlineStr,proto3" json:"deadline_str,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProposalRequest) Reset() {
	*x = CreateProposalRequest{}
	mi := &file_proto_proposal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProposalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProposalRequest) ProtoMessage() {}

func (x *CreateProposalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proposal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProposalRequest.ProtoReflect.Descriptor instead.
func (*CreateProposalRequest) Descriptor() ([]byte, []int) {
	return file_proto_proposal_proto_rawDescGZIP(), []int{0}
}

func (x *CreateProposalRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *CreateProposalRequest) GetFreelancerId() string {
	if x != nil {
		return x.FreelancerId
	}
	return ""
}

func (x *CreateProposalRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *CreateProposalRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateProposalRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateProposalRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateProposalRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *CreateProposalRequest) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *CreateProposalRequest) GetDeadlineStr() string {
	if x != nil {
		return x.DeadlineStr
	}
	return ""
}

type CreateProposalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProposalId    string                 `protobuf:"bytes,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProposalResponse) Reset() {
	*x = CreateProposalResponse{}
	mi := &file_proto_proposal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProposalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProposalResponse) ProtoMessage() {}

func (x *CreateProposalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proposal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProposalResponse.ProtoReflect.Descriptor instead.
func (*CreateProposalResponse) Descriptor() ([]byte, []int) {
	return file_proto_proposal_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProposalResponse) GetProposalId() string {
	if x != nil {
		return x.ProposalId
	}
	return ""
}

func (x *CreateProposalResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetProposalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProposalId    string                 `protobuf:"bytes,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProposalRequest) Reset() {
	*x = GetProposalRequest{}
	mi := &file_proto_proposal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProposalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProposalRequest) ProtoMessage() {}

func (x *GetProposalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proposal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProposalRequest.ProtoReflect.Descriptor instead.
func (*GetProposalRequest) Descriptor() ([]byte, []int) {
	return file_proto_proposal_proto_rawDescGZIP(), []int{2}
}

func (x *GetProposalRequest) GetProposalId() string {
	if x != nil {
		return x.ProposalId
	}
	return ""
}

type GetProposalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProposalId    string                 `protobuf:"bytes,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	FreelancerId  string                 `protobuf:"bytes,3,opt,name=freelancer_id,json=freelancerId,proto3" json:"freelancer_id,omitempty"`
	TemplateId    string                 `protobuf:"bytes,4,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Version       int32                  `protobuf:"varint,8,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=deadline,proto3" json:"deadline,omitempty"`
	DeadlineStr   string                 `protobuf:"bytes,12,opt,name=deadline_str,json=deadlineStr,proto3" json:"deadline_str,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProposalResponse) Reset() {
	*x = GetProposalResponse{}
	mi := &file_proto_proposal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProposalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProposalResponse) ProtoMessage() {}

func (x *GetProposalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proposal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProposalResponse.ProtoReflect.Descriptor instead.
func (*GetProposalResponse) Descriptor() ([]byte, []int) {
	return file_proto_proposal_proto_rawDescGZIP(), []int{3}
}

func (x *GetProposalResponse) GetProposalId() string {
	if x != nil {
		return x.ProposalId
	}
	return ""
}

func (x *GetProposalResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *GetProposalResponse) GetFreelancerId() string {
	if x != nil {
		return x.FreelancerId
	}
	return ""
}

func (x *GetProposalResponse) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *GetProposalResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetProposalResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GetProposalResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetProposalResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetProposalResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetProposalResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *GetProposalResponse) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *GetProposalResponse) GetDeadlineStr() string {
	if x != nil {
		return x.DeadlineStr
	}
	return ""
}

type UpdateProposalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProposalId    string                 `protobuf:"bytes,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Version       int32                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=deadline,proto3" json:"deadline,omitempty"`
	DeadlineStr   string                 `protobuf:"bytes,6,opt,name=deadline_str,json=deadlineStr,proto3" json:"deadline_str,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProposalRequest) Reset() {
	*x = UpdateProposalRequest{}
	mi := &file_proto_proposal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProposalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProposalRequest) ProtoMessage() {}

func (x *UpdateProposalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proposal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProposalRequest.ProtoReflect.Descriptor instead.
func (*UpdateProposalRequest) Descriptor() ([]byte, []int) {
	return file_proto_proposal_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateProposalRequest) GetProposalId() string {
	if x != nil {
		return x.ProposalId
	}
	return ""
}

func (x *UpdateProposalRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateProposalRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateProposalRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *UpdateProposalRequest) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *UpdateProposalRequest) GetDeadlineStr() string {
	if x != nil {
		return x.DeadlineStr
	}
	return ""
}

type UpdateProposalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProposalId    string                 `protobuf:"bytes,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	NewVersion    int32                  `protobuf:"varint,3,opt,name=new_version,json=newVersion,proto3" json:"new_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProposalResponse) Reset() {
	*x = UpdateProposalResponse{}
	mi := &file_proto_proposal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProposalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProposalResponse) ProtoMessage() {}

func (x *UpdateProposalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proposal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProposalResponse.ProtoReflect.Descriptor instead.
func (*UpdateProposalResponse) Descriptor() ([]byte, []int) {
	return file_proto_proposal_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateProposalResponse) GetProposalId() string {
	if x != nil {
		return x.ProposalId
	}
	return ""
}

func (x *UpdateProposalResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateProposalResponse) GetNewVersion() int32 {
	if x != nil {
		return x.NewVersion
	}
	return 0
}

type SaveTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FreelancerId  string                 `protobuf:"bytes,1,opt,name=freelancer_id,json=freelancerId,proto3" json:"freelancer_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveTemplateRequest) Reset() {
	*x = SaveTemplateRequest{}
	mi := &file_proto_proposal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveTemplateRequest) ProtoMessage() {}

func (x *SaveTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proposal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveTemplateRequest.ProtoReflect.Descriptor instead.
func (*SaveTemplateRequest) Descriptor() ([]byte, []int) {
	return file_proto_proposal_proto_rawDescGZIP(), []int{6}
}

func (x *SaveTemplateRequest) GetFreelancerId() string {
	if x != nil {
		return x.FreelancerId
	}
	return ""
}

func (x *SaveTemplateRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SaveTemplateRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type SaveTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveTemplateResponse) Reset() {
	*x = SaveTemplateResponse{}
	mi := &file_proto_proposal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveTemplateResponse) ProtoMessage() {}

func (x *SaveTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proposal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveTemplateResponse.ProtoReflect.Descriptor instead.
func (*SaveTemplateResponse) Descriptor() ([]byte, []int) {
	return file_proto_proposal_proto_rawDescGZIP(), []int{7}
}

func (x *SaveTemplateResponse) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *SaveTemplateResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetTemplatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FreelancerId  string                 `protobuf:"bytes,1,opt,name=freelancer_id,json=freelancerId,proto3" json:"freelancer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTemplatesRequest) Reset() {
	*x = GetTemplatesRequest{}
	mi := &file_proto_proposal_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemplatesRequest) ProtoMessage() {}

func (x *GetTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proposal_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemplatesRequest.ProtoReflect.Descriptor instead.
func (*GetTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_proto_proposal_proto_rawDescGZIP(), []int{8}
}

func (x *GetTemplatesRequest) GetFreelancerId() string {
	if x != nil {
		return x.FreelancerId
	}
	return ""
}

type GetTemplatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Templates     []*Template            `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTemplatesResponse) Reset() {
	*x = GetTemplatesResponse{}
	mi := &file_proto_proposal_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemplatesResponse) ProtoMessage() {}

func (x *GetTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proposal_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemplatesResponse.ProtoReflect.Descriptor instead.
func (*GetTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_proto_proposal_proto_rawDescGZIP(), []int{9}
}

func (x *GetTemplatesResponse) GetTemplates() []*Template {
	if x != nil {
		return x.Templates
	}
	return nil
}

type Template struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Template) Reset() {
	*x = Template{}
	mi := &file_proto_proposal_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Template) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Template) ProtoMessage() {}

func (x *Template) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proposal_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Template.ProtoReflect.Descriptor instead.
func (*Template) Descriptor() ([]byte, []int) {
	return file_proto_proposal_proto_rawDescGZIP(), []int{10}
}

func (x *Template) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *Template) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Template) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ListProposalsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	FreelancerId  string                 `protobuf:"bytes,2,opt,name=freelancer_id,json=freelancerId,proto3" json:"freelancer_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Skip          int64                  `protobuf:"varint,4,opt,name=skip,proto3" json:"skip,omitempty"`
	Limit         int64                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProposalsRequest) Reset() {
	*x = ListProposalsRequest{}
	mi := &file_proto_proposal_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProposalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProposalsRequest) ProtoMessage() {}

func (x *ListProposalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proposal_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProposalsRequest.ProtoReflect.Descriptor instead.
func (*ListProposalsRequest) Descriptor() ([]byte, []int) {
	return file_proto_proposal_proto_rawDescGZIP(), []int{11}
}

func (x *ListProposalsRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ListProposalsRequest) GetFreelancerId() string {
	if x != nil {
		return x.FreelancerId
	}
	return ""
}

func (x *ListProposalsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListProposalsRequest) GetSkip() int64 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *ListProposalsRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListProposalsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proposals     []*Proposal            `protobuf:"bytes,1,rep,name=proposals,proto3" json:"proposals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProposalsResponse) Reset() {
	*x = ListProposalsResponse{}
	mi := &file_proto_proposal_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProposalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProposalsResponse) ProtoMessage() {}

func (x *ListProposalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proposal_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProposalsResponse.ProtoReflect.Descriptor instead.
func (*ListProposalsResponse) Descriptor() ([]byte, []int) {
	return file_proto_proposal_proto_rawDescGZIP(), []int{12}
}

func (x *ListProposalsResponse) GetProposals() []*Proposal {
	if x != nil {
		return x.Proposals
	}
	return nil
}

type Proposal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProposalId    string                 `protobuf:"bytes,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	FreelancerId  string                 `protobuf:"bytes,3,opt,name=freelancer_id,json=freelancerId,proto3" json:"freelancer_id,omitempty"`
	TemplateId    string                 `protobuf:"bytes,4,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Version       int32                  `protobuf:"varint,8,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Proposal) Reset() {
	*x = Proposal{}
	mi := &file_proto_proposal_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proposal) ProtoMessage() {}

func (x *Proposal) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proposal_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proposal.ProtoReflect.Descriptor instead.
func (*Proposal) Descriptor() ([]byte, []int) {
	return file_proto_proposal_proto_rawDescGZIP(), []int{13}
}

func (x *Proposal) GetProposalId() string {
	if x != nil {
		return x.ProposalId
	}
	return ""
}

func (x *Proposal) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Proposal) GetFreelancerId() string {
	if x != nil {
		return x.FreelancerId
	}
	return ""
}

func (x *Proposal) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *Proposal) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Proposal) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Proposal) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Proposal) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Proposal) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Proposal) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_proto_proposal_proto protoreflect.FileDescriptor

const file_proto_proposal_proto_rawDesc = "" +
	"\n" +
	"\x14proto/proposal.proto\x12\bproposal\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb7\x02\n" +
	"\x15CreateProposalRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12#\n" +
	"\rfreelancer_id\x18\x02 \x01(\tR\ffreelancerId\x12\x1f\n" +
	"\vtemplate_id\x18\x03 \x01(\tR\n" +
	"templateId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\a \x01(\x05R\aversion\x126\n" +
	"\bdeadline\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\x12!\n" +
	"\fdeadline_str\x18\t \x01(\tR\vdeadlineStr\"Q\n" +
	"\x16CreateProposalResponse\x12\x1f\n" +
	"\vproposal_id\x18\x01 \x01(\tR\n" +
	"proposalId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"5\n" +
	"\x12GetProposalRequest\x12\x1f\n" +
	"\vproposal_id\x18\x01 \x01(\tR\n" +
	"proposalId\"\xcc\x03\n" +
	"\x13GetProposalResponse\x12\x1f\n" +
	"\vproposal_id\x18\x01 \x01(\tR\n" +
	"proposalId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12#\n" +
	"\rfreelancer_id\x18\x03 \x01(\tR\ffreelancerId\x12\x1f\n" +
	"\vtemplate_id\x18\x04 \x01(\tR\n" +
	"templateId\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\b \x01(\x05R\aversion\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x126\n" +
	"\bdeadline\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\x12!\n" +
	"\fdeadline_str\x18\f \x01(\tR\vdeadlineStr\"\xdd\x01\n" +
	"\x15UpdateProposalRequest\x12\x1f\n" +
	"\vproposal_id\x18\x01 \x01(\tR\n" +
	"proposalId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x05R\aversion\x126\n" +
	"\bdeadline\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\x12!\n" +
	"\fdeadline_str\x18\x06 \x01(\tR\vdeadlineStr\"r\n" +
	"\x16UpdateProposalResponse\x12\x1f\n" +
	"\vproposal_id\x18\x01 \x01(\tR\n" +
	"proposalId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1f\n" +
	"\vnew_version\x18\x03 \x01(\x05R\n" +
	"newVersion\"j\n" +
	"\x13SaveTemplateRequest\x12#\n" +
	"\rfreelancer_id\x18\x01 \x01(\tR\ffreelancerId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"O\n" +
	"\x14SaveTemplateResponse\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\":\n" +
	"\x13GetTemplatesRequest\x12#\n" +
	"\rfreelancer_id\x18\x01 \x01(\tR\ffreelancerId\"H\n" +
	"\x14GetTemplatesResponse\x120\n" +
	"\ttemplates\x18\x01 \x03(\v2\x12.proposal.TemplateR\ttemplates\"[\n" +
	"\bTemplate\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"\x9a\x01\n" +
	"\x14ListProposalsRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12#\n" +
	"\rfreelancer_id\x18\x02 \x01(\tR\ffreelancerId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x12\n" +
	"\x04skip\x18\x04 \x01(\x03R\x04skip\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x03R\x05limit\"I\n" +
	"\x15ListProposalsResponse\x120\n" +
	"\tproposals\x18\x01 \x03(\v2\x12.proposal.ProposalR\tproposals\"\xe6\x02\n" +
	"\bProposal\x12\x1f\n" +
	"\vproposal_id\x18\x01 \x01(\tR\n" +
	"proposalId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12#\n" +
	"\rfreelancer_id\x18\x03 \x01(\tR\ffreelancerId\x12\x1f\n" +
	"\vtemplate_id\x18\x04 \x01(\tR\n" +
	"templateId\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\b \x01(\x05R\aversion\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2\x88\x04\n" +
	"\x0fProposalService\x12S\n" +
	"\x0eCreateProposal\x12\x1f.proposal.CreateProposalRequest\x1a .proposal.CreateProposalResponse\x12N\n" +
	"\x0fGetProposalByID\x12\x1c.proposal.GetProposalRequest\x1a\x1d.proposal.GetProposalResponse\x12S\n" +
	"\x0eUpdateProposal\x12\x1f.proposal.UpdateProposalRequest\x1a .proposal.UpdateProposalResponse\x12M\n" +
	"\fSaveTemplate\x12\x1d.proposal.SaveTemplateRequest\x1a\x1e.proposal.SaveTemplateResponse\x12Z\n" +
	"\x19GetTemplatesForFreelancer\x12\x1d.proposal.GetTemplatesRequest\x1a\x1e.proposal.GetTemplatesResponse\x12P\n" +
	"\rListProposals\x12\x1e.proposal.ListProposalsRequest\x1a\x1f.proposal.ListProposalsResponseB\x12Z\x10./proto;proposalb\x06proto3"

var (
	file_proto_proposal_proto_rawDescOnce sync.Once
	file_proto_proposal_proto_rawDescData []byte
)

func file_proto_proposal_proto_rawDescGZIP() []byte {
	file_proto_proposal_proto_rawDescOnce.Do(func() {
		file_proto_proposal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_proposal_proto_rawDesc), len(file_proto_proposal_proto_rawDesc)))
	})
	return file_proto_proposal_proto_rawDescData
}

var file_proto_proposal_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_proposal_proto_goTypes = []any{
	(*CreateProposalRequest)(nil),  // 0: proposal.CreateProposalRequest
	(*CreateProposalResponse)(nil), // 1: proposal.CreateProposalResponse
	(*GetProposalRequest)(nil),     // 2: proposal.GetProposalRequest
	(*GetProposalResponse)(nil),    // 3: proposal.GetProposalResponse
	(*UpdateProposalRequest)(nil),  // 4: proposal.UpdateProposalRequest
	(*UpdateProposalResponse)(nil), // 5: proposal.UpdateProposalResponse
	(*SaveTemplateRequest)(nil),    // 6: proposal.SaveTemplateRequest
	(*SaveTemplateResponse)(nil),   // 7: proposal.SaveTemplateResponse
	(*GetTemplatesRequest)(nil),    // 8: proposal.GetTemplatesRequest
	(*GetTemplatesResponse)(nil),   // 9: proposal.GetTemplatesResponse
	(*Template)(nil),               // 10: proposal.Template
	(*ListProposalsRequest)(nil),   // 11: proposal.ListProposalsRequest
	(*ListProposalsResponse)(nil),  // 12: proposal.ListProposalsResponse
	(*Proposal)(nil),               // 13: proposal.Proposal
	(*timestamppb.Timestamp)(nil),  // 14: google.protobuf.Timestamp
}
var file_proto_proposal_proto_depIdxs = []int32{
	14, // 0: proposal.CreateProposalRequest.deadline:type_name -> google.protobuf.Timestamp
	14, // 1: proposal.GetProposalResponse.created_at:type_name -> google.protobuf.Timestamp
	14, // 2: proposal.GetProposalResponse.updated_at:type_name -> google.protobuf.Timestamp
	14, // 3: proposal.GetProposalResponse.deadline:type_name -> google.protobuf.Timestamp
	14, // 4: proposal.UpdateProposalRequest.deadline:type_name -> google.protobuf.Timestamp
	10, // 5: proposal.GetTemplatesResponse.templates:type_name -> proposal.Template
	13, // 6: proposal.ListProposalsResponse.proposals:type_name -> proposal.Proposal
	14, // 7: proposal.Proposal.created_at:type_name -> google.protobuf.Timestamp
	14, // 8: proposal.Proposal.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 9: proposal.ProposalService.CreateProposal:input_type -> proposal.CreateProposalRequest
	2,  // 10: proposal.ProposalService.GetProposalByID:input_type -> proposal.GetProposalRequest
	4,  // 11: proposal.ProposalService.UpdateProposal:input_type -> proposal.UpdateProposalRequest
	6,  // 12: proposal.ProposalService.SaveTemplate:input_type -> proposal.SaveTemplateRequest
	8,  // 13: proposal.ProposalService.GetTemplatesForFreelancer:input_type -> proposal.GetTemplatesRequest
	11, // 14: proposal.ProposalService.ListProposals:input_type -> proposal.ListProposalsRequest
	1,  // 15: proposal.ProposalService.CreateProposal:output_type -> proposal.CreateProposalResponse
	3,  // 16: proposal.ProposalService.GetProposalByID:output_type -> proposal.GetProposalResponse
	5,  // 17: proposal.ProposalService.UpdateProposal:output_type -> proposal.UpdateProposalResponse
	7,  // 18: proposal.ProposalService.SaveTemplate:output_type -> proposal.SaveTemplateResponse
	9,  // 19: proposal.ProposalService.GetTemplatesForFreelancer:output_type -> proposal.GetTemplatesResponse
	12, // 20: proposal.ProposalService.ListProposals:output_type -> proposal.ListProposalsResponse
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_proposal_proto_init() }
func file_proto_proposal_proto_init() {
	if File_proto_proposal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_proposal_proto_rawDesc), len(file_proto_proposal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_proposal_proto_goTypes,
		DependencyIndexes: file_proto_proposal_proto_depIdxs,
		MessageInfos:      file_proto_proposal_proto_msgTypes,
	}.Build()
	File_proto_proposal_proto = out.File
	file_proto_proposal_proto_goTypes = nil
	file_proto_proposal_proto_depIdxs = nil
}
